name: master
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      ######
      ######
      # SSH 設定
      - name: backstage
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: backstage.key
          known_hosts: ${{ secrets.SSH_KNOWN_HOST }}
          config: |
            Host backstage
              HostName ${{ secrets.SSH_HOST_NAME }}
              User ${{ secrets.SSH_USER }}
              IdentityFile ~/.ssh/backstage.key
              Port 22
              StrictHostKeyChecking no
      ######
      ######
      - name: Connect server to master, Other ( pull, build etc... )
        run: |
          ssh backstage \
          "\
            cd backstage/public/feature && \
            git reset --hard HEAD && \
            git pull origin master && \
            git checkout master && \
            docker compose exec patreon_web npm install --prefix ./public/feature && \
            docker compose exec patreon_web npm run build --prefix ./public/feature
          "